                                       -- Assignment Questions --
-- PART 1 — Basic Window Functions
-- 1. Assign row numbers for each customer based on order date.
      SELECT CUSTOMER_NAME,ORDER_DATE,
       ROW_NUMBER() OVER (PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE ) AS ROWNUB
	FROM ASSIGNMENT_ecommerce_orders;
    
-- 2. Rank customers based on highest sales amount.
      SELECT CUSTOMER_NAME,MAX(SALES_AMOUNT) AS HIGHEST_SALES,
      RANK () OVER  (ORDER BY MAX(SALES_AMOUNT)DESC ) AS RANK_NUB
	FROM ASSIGNMENT_ecommerce_orders
     GROUP BY CUSTOMER_NAME;
     
-- 3. Find dense rank of products within each category.
      SELECT PRODUCT_NAME,CATEGORY,
        DENSE_RANK () OVER ( PARTITION BY CATEGORY ORDER BY  PRODUCT_NAME) AS DENRANK 
	FROM ASSIGNMENT_ecommerce_orders;
    
-- 4. Find duplicate sales amounts using RANK() and DENSE_RANK().
    SELECT SALES_AMOUNT, COUNT(*) AS TOTAL_COUNT ,
           RANK() OVER( ORDER BY COUNT(*) DESC) AS RNK,
           DENSE_RANK() OVER( ORDER BY COUNT(*) DESC) AS DRNK
    FROM ASSIGNMENT_ecommerce_orders
GROUP BY  SALES_AMOUNT  ;

-- 5. Display previous purchase amount for every customer using LAG().
    SELECT CUSTOMER_NAME,ORDER_DATE, SALES_AMOUNT,
       LAG(SALES_AMOUNT) OVER (PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS PREVIOUS_SALE
	FROM ASSIGNMENT_ecommerce_orders; 
    
-- 6. Display next purchase amount using LEAD().
      SELECT CUSTOMER_NAME , ORDER_DATE,SALES_AMOUNT ,
       LEAD(SALES_AMOUNT) OVER (PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS NEXT_SALE
   FROM ASSIGNMENT_ecommerce_orders; 
   
-- 7. Find sales difference between current and previous purchase.
       SELECT CUSTOMER_NAME , ORDER_DATE,SALES_AMOUNT ,
	LAG(SALES_AMOUNT) OVER (PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS PREVIOUS_SALE,
    LEAD(SALES_AMOUNT) OVER (PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS NEXT_SALE,
      SALES_AMOUNT - (LAG(SALES_AMOUNT) OVER (PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE)) AS SALES_DIFF
  FROM ASSIGNMENT_ecommerce_orders; 
  
-- 8. Find percentage increase/decrease from previous purchase.
      SELECT 
    CUSTOMER_NAME,
    ORDER_DATE,
    SALES_AMOUNT,
    LAG(SALES_AMOUNT) OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS PREVIOUS_SALE,
  CONCAT(ROUND(((SALES_AMOUNT - LAG(SALES_AMOUNT) OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE)) /
	LAG(SALES_AMOUNT) OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE)) * 100,2),'%') AS PERCENTAGE_CHANGE
FROM ASSIGNMENT_ecommerce_orders;

-- PART 2 — Running & Rolling Calculations
-- 9. Calculate running total sales for each customer.
	SELECT CUSTOMER_NAME,ORDER_DATE,SALES_AMOUNT,
      SUM(SALES_AMOUNT) OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS RUNNING_SALES
    FROM ASSIGNMENT_ecommerce_orders;
  
-- 10. Calculate cumulative sales month-wise.
   SELECT MONTH(ORDER_DATE) AS MONTH_DATE,SALES_AMOUNT,
     SUM(SALES_AMOUNT) OVER(ORDER BY MONTH(ORDER_DATE)) AS CUM_SALES
  FROM ASSIGNMENT_ecommerce_orders;   
     
-- 11. Calculate rolling 3-day sales.
     SELECT ORDER_DATE, SALES_AMOUNT,
      SUM(SALES_AMOUNT) OVER (
      ORDER BY ORDER_DATE
      ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) AS ROLLING_3DAY_SALES
	FROM ASSIGNMENT_ecommerce_orders;  
     
-- 12. Calculate rolling 3-order average sales.
     SELECT ORDER_DATE, SALES_AMOUNT,
      AVG(SALES_AMOUNT) OVER (
	  ORDER BY ORDER_DATE
      ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) AS ROLLING_AVG
	FROM ASSIGNMENT_ecommerce_orders;  
    
-- 13. Find moving average sales for each customer.
      SELECT CUSTOMER_NAME, ORDER_DATE, SALES_AMOUNT,
       AVG(SALES_AMOUNT) OVER ( PARTITION BY CUSTOMER_NAME
       ORDER BY ORDER_DATE
       ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) AS MOVING_AVG
	FROM ASSIGNMENT_ecommerce_orders;  
    
-- 14. Calculate cumulative category sales.
   SELECT CATEGORY,SALES_AMOUNT,ORDER_DATE,
    SUM(SALES_AMOUNT)  OVER (PARTITION BY CATEGORY 
    ORDER BY ORDER_DATE
    ) AS CUM_CATE_SALES
   FROM ASSIGNMENT_ecommerce_orders;  
   
-- PART 3 — FIRST_VALUE / LAST_VALUE
-- 15. Find first purchase amount of every customer.
SELECT CUSTOMER_NAME,ORDER_DATE,SALES_AMOUNT,
   FIRST_VALUE(SALES_AMOUNT) OVER ( PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS FST_VALUE
FROM ASSIGNMENT_ecommerce_orders;

-- 16. Find latest purchase amount of every customer.
	SELECT CUSTOMER_NAME,ORDER_DATE,SALES_AMOUNT,
   FIRST_VALUE(SALES_AMOUNT) OVER ( PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE DESC) AS LATEST_PUR
FROM ASSIGNMENT_ecommerce_orders;

 SELECT CUSTOMER_NAME,ORDER_DATE,SALES_AMOUNT,
   LAST_VALUE(SALES_AMOUNT) OVER ( PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE 
   ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING  ) AS LATEST_PUR
FROM ASSIGNMENT_ecommerce_orders;

-- 17. Find first product purchased in each category.
     SELECT ORDER_DATE,CATEGORY,PRODUCT_NAME,
     FIRST_VALUE(PRODUCT_NAME) OVER ( PARTITION BY CATEGORY ORDER BY ORDER_DATE) AS FIRST_PUR_PDT
FROM ASSIGNMENT_ecommerce_orders;

-- 18. Find last product purchased by each customer.
      SELECT ORDER_DATE,CUSTOMER_NAME,PRODUCT_NAME,
        LAST_VALUE(PRODUCT_NAME) OVER (PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE
	    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING  ) AS LAST_PDT_PUR
      FROM ASSIGNMENT_ecommerce_orders;
      
-- 19. Compare current purchase with first purchase.
       SELECT ORDER_DATE,CUSTOMER_NAME,SALES_AMOUNT,
         FIRST_VALUE(SALES_AMOUNT) OVER ( PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE
         ROWS BETWEEN  UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS FST_PUR
       FROM ASSIGNMENT_ecommerce_orders;
       
-- 20. Compare current purchase with latest purchase
        SELECT ORDER_DATE,CUSTOMER_NAME,SALES_AMOUNT,
         LAST_VALUE(SALES_AMOUNT) OVER ( PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE
         ROWS BETWEEN  UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS FST_PUR
       FROM ASSIGNMENT_ecommerce_orders;
       
-- PART 4 — NTILE / Percentile Functions
-- 21. Divide customers into 4 spending groups using NTILE(4).
     SELECT CUSTOMER_NAME,SALES_AMOUNT ,
        NTILE(4) OVER ( ORDER BY SALES_AMOUNT DESC)  AS SPENDING_GRP
      FROM ASSIGNMENT_ecommerce_orders;  
      
-- 22. Find top 25% customers based on sales.
  SELECT *FROM (
    SELECT CUSTOMER_NAME,SUM(SALES_AMOUNT) AS TOTAL_SALES,
    NTILE(4) OVER(ORDER BY SUM(SALES_AMOUNT) DESC) AS SALES_GROUP
  FROM ASSIGNMENT_ecommerce_orders
    GROUP BY CUSTOMER_NAME
) TOP_CUSTOMERS
WHERE SALES_GROUP = 1;
        
SELECT CUSTOMER_NAME,SALES_AMOUNT ,
  NTILE(4) OVER ( ORDER BY SALES_AMOUNT DESC)  AS QUARTER_SALES
FROM ASSIGNMENT_ecommerce_orders;  
      
-- 23. Calculate PERCENT_RANK() for sales amount.
       SELECT SALES_AMOUNT,
        PERCENT_RANK() OVER ( ORDER BY SALES_AMOUNT) AS PERCENT_RNK
	FROM ASSIGNMENT_ecommerce_orders;  
    
-- 24. Calculate CUME_DIST() for customer sales.
       SELECT CUSTOMER_NAME , SALES_AMOUNT,
        ROUND(CUME_DIST() OVER (PARTITION BY CUSTOMER_NAME ORDER BY SALES_AMOUNT),4) AS CUME_DISTRIBUTION
     FROM ASSIGNMENT_ecommerce_orders;     
     
-- 25. Identify customers whose sales fall above 80% distribution.
    SELECT *FROM (
    SELECT CUSTOMER_NAME,SUM(SALES_AMOUNT) AS TOTAL_SALES,
	CUME_DIST() OVER( ORDER BY SUM(SALES_AMOUNT)) AS SALES_DISTRIBUTION
   FROM ASSIGNMENT_ecommerce_orders
    GROUP BY CUSTOMER_NAME
) AS SALES_FALL
WHERE SALES_DISTRIBUTION > 0.80;

-- PART 5 — Window Frames
-- 26. Calculate running total using:
-- ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    SELECT CUSTOMER_NAME, SALES_AMOUNT,
      SUM(SALES_AMOUNT) OVER (  ORDER BY ORDER_DATE
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING_SALES
     FROM ASSIGNMENT_ecommerce_orders;    
     
-- 27. Calculate next 2 orders sales using:
-- ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING
	SELECT ORDER_DATE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER (  ORDER BY ORDER_DATE
      ROWS BETWEEN  CURRENT ROW AND 2 FOLLOWING) AS NEXT_2_SALES
     FROM ASSIGNMENT_ecommerce_orders;    
     
-- 28. Calculate previous 2 orders sales using:
-- ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
   SELECT ORDER_DATE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER (  ORDER BY ORDER_DATE
       ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS PRV_2_SALES
     FROM ASSIGNMENT_ecommerce_orders;    
     
-- 29. Find centered moving average using:
-- ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING
     SELECT ORDER_DATE,SALES_AMOUNT,
    AVG(SALES_AMOUNT) OVER (  ORDER BY ORDER_DATE
     ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING ) AS MOVING_SALES
     FROM ASSIGNMENT_ecommerce_orders;  
     
-- 30. Compare all window frame outputs in one query.
        SELECT CUSTOMER_NAME , SALES_AMOUNT,ORDER_DATE,
        SUM(SALES_AMOUNT) OVER (  ORDER BY ORDER_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING_SALES,
       SUM(SALES_AMOUNT) OVER (  ORDER BY ORDER_DATE ROWS BETWEEN  CURRENT ROW AND 2 FOLLOWING) AS NEXT_2_SALES,
       SUM(SALES_AMOUNT) OVER (  ORDER BY ORDER_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS PRV_2_SALES,
       AVG(SALES_AMOUNT) OVER (  ORDER BY ORDER_DATE ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING ) AS MOVING_SALES
      FROM ASSIGNMENT_ecommerce_orders;    
     
-- PART 6 — Real-Time Business Scenarios
-- 31. Find top 3 highest sales every month.
 SELECT MONTH(ORDER_DATE) ,MAX(SALES_AMOUNT) AS MAX_SALES,
	DENSE_RANK() OVER(ORDER BY MAX(SALES_AMOUNT)  DESC ) AS DEN_RNK
 FROM ASSIGNMENT_ecommerce_orders
 GROUP BY MONTH(ORDER_DATE) ; 
 
-- 32. Find customer who purchased continuously for 3 months.
   WITH CTE AS (
     SELECT MONTH(ORDER_DATE) AS MONTH_NO,CUSTOMER_NAME,ORDER_DATE,
      ROW_NUMBER() OVER (PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS RN
	FROM ASSIGNMENT_ecommerce_orders
    )
    SELECT * FROM CTE; 
    
-- 33. Find repeat customers.
       SELECT ORDER_DATE,CUSTOMER_NAME,
	    COUNT(*) OVER( PARTITION BY CUSTOMER_NAME) AS TOTAL_ORDERS
      FROM ASSIGNMENT_ecommerce_orders ;
      
-- 34. Find customers whose current purchase is lower than previous purchase.
    SELECT * FROM (
    SELECT CUSTOMER_NAME,ORDER_DATE,SALES_AMOUNT,
   LAG(SALES_AMOUNT)OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS PREVIOUS_PURCHASE
  FROM ASSIGNMENT_ecommerce_orders 
) AS LOW_PRE_PURCHASE
WHERE SALES_AMOUNT < PREVIOUS_PURCHASE;

-- 35. Find highest selling category every month.
SELECT *FROM (
    SELECT MONTH(ORDER_DATE) AS MONTH_NO,CATEGORY,
	 SUM(SALES_AMOUNT) AS TOTAL_SALES,RANK() OVER(PARTITION BY MONTH(ORDER_DATE)ORDER BY SUM(SALES_AMOUNT) DESC) AS RNK
  FROM ASSIGNMENT_ecommerce_orders
    GROUP BY MONTH(ORDER_DATE), CATEGORY
) AS HIGH_SELL
WHERE RNK = 1;

-- 36. Find contribution % of each order to total monthly sales.
SELECT ORDER_ID,CUSTOMER_NAME,ORDER_DATE,SALES_AMOUNT,
  SUM(SALES_AMOUNT) OVER(PARTITION BY MONTH(ORDER_DATE)) AS MONTH_TOTAL,
  ROUND(SALES_AMOUNT * 100 / SUM(SALES_AMOUNT) OVER(PARTITION BY MONTH(ORDER_DATE)),2) AS CONTRIBUTION_PERCENT
FROM ASSIGNMENT_ecommerce_orders ;

-- 37. Find customers contributing highest revenue.
SELECT *FROM (
    SELECT CUSTOMER_NAME,SUM(SALES_AMOUNT) AS TOTAL_REVENUE,
    DENSE_RANK() OVER(ORDER BY SUM(SALES_AMOUNT) DESC) AS RNK
  FROM ASSIGNMENT_ecommerce_orders 
    GROUP BY CUSTOMER_NAME
) HIGH_REVENUE
WHERE RNK = 1;

-- 38. Identify low-performing months.
   SELECT *FROM (
    SELECT MONTH(ORDER_DATE) AS MONTH_NO,SUM(SALES_AMOUNT) AS TOTAL_SALES,AVG(SUM(SALES_AMOUNT))OVER() AS AVG_MONTH_SALES
  FROM ASSIGNMENT_ecommerce_orders 
    GROUP BY MONTH(ORDER_DATE)
) LOW_PER_MONTH
WHERE TOTAL_SALES < AVG_MONTH_SALES;

-- 39. Find purchase gap between consecutive orders.
  SELECT CUSTOMER_NAME,ORDER_DATE,
   LAG(ORDER_DATE) OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS PREVIOUS_ORDER_DATE,
   DATEDIFF(ORDER_DATE,LAG(ORDER_DATE)OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE)) AS GAP_DAYS
  FROM ASSIGNMENT_ecommerce_orders ;

-- 40. Find customers whose sales are continuously increasing.
   SELECT * FROM (
    SELECT CUSTOMER_NAME,ORDER_DATE,SALES_AMOUNT,
    LAG(SALES_AMOUNT,1)OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS PREV1,
    LAG(SALES_AMOUNT,2)OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS PREV2
  FROM  ASSIGNMENT_ecommerce_orders
) AS CON_INCREASE
WHERE SALES_AMOUNT > PREV1
AND PREV1 > PREV2;

-- Advanced Questions
-- 41. Find second highest purchase of every customer.
SELECT *FROM (
    SELECT CUSTOMER_NAME,SALES_AMOUNT,
    DENSE_RANK() OVER(PARTITION BY CUSTOMER_NAME ORDER BY SALES_AMOUNT DESC) AS RNK
FROM ASSIGNMENT_ecommerce_orders 
) HIGH_PUR
WHERE RNK = 2;

-- 42. Find nth highest sales using window functions.
   SELECT DISTINCT CATEGORY,
   NTH_VALUE(SALES_AMOUNT,1)OVER(PARTITION BY CATEGORY ORDER BY SALES_AMOUNT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS HIGHEST_SALES
FROM ASSIGNMENT_ecommerce_orders ;

-- 43. Remove duplicates using ROW_NUMBER().
SELECT *FROM (
    SELECT *,ROW_NUMBER() OVER(PARTITION BY CUSTOMER_NAME, ORDER_DATE, SALES_AMOUNT ORDER BY ORDER_ID) AS RN
FROM ASSIGNMENT_ecommerce_orders 
) AS REMOVE_DUP
WHERE RN = 1;

-- 44. Find first and last purchase date of each customer.
   SELECT DISTINCT CUSTOMER_NAME,
  FIRST_VALUE(ORDER_DATE)OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS FIRST_PURCHASE,
  LAST_VALUE(ORDER_DATE) OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE 
  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_PURCHASE
  FROM ASSIGNMENT_ecommerce_orders ;
  
-- 45. Find highest purchase growth month-over-month.
SELECT *FROM (
    SELECT MONTH(ORDER_DATE) AS MONTH_NO,SUM(SALES_AMOUNT) AS CURRENT_MONTH_SALES,
    LAG(SUM(SALES_AMOUNT))OVER(ORDER BY MONTH(ORDER_DATE)) AS PREVIOUS_MONTH_SALES
FROM ASSIGNMENT_ecommerce_orders 
    GROUP BY MONTH(ORDER_DATE)
) AS  MONTH_OVER_MONTH
ORDER BY (CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES) DESC
LIMIT 1;

-- 46. Find customers whose purchase amount is above customer average.
SELECT *FROM (
    SELECT CUSTOMER_NAME,ORDER_DATE,SALES_AMOUNT,
    AVG(SALES_AMOUNT)OVER(PARTITION BY CUSTOMER_NAME) AS AVG_PURCHASE
FROM ASSIGNMENT_ecommerce_orders 
) AS CUSTOMER_AVG
WHERE SALES_AMOUNT > AVG_PURCHASE;

-- 47. Find monthly sales trend using LAG().
  SELECT MONTH(ORDER_DATE) AS MONTH_NO, SUM(SALES_AMOUNT) AS CURRENT_MONTH_SALES,
     LAG(SUM(SALES_AMOUNT))OVER(ORDER BY MONTH(ORDER_DATE)) AS PREVIOUS_MONTH_SALES
   FROM ASSIGNMENT_ecommerce_orders 
GROUP BY MONTH(ORDER_DATE);

-- 48. Compare each month's sales with previous month.
   SELECT MONTH(ORDER_DATE) AS MONTH_NO,SUM(SALES_AMOUNT) AS CURRENT_MONTH_SALES,
  LAG(SUM(SALES_AMOUNT))OVER(ORDER BY MONTH(ORDER_DATE)) AS PREVIOUS_MONTH_SALES,
  SUM(SALES_AMOUNT) - LAG(SUM(SALES_AMOUNT))OVER(ORDER BY MONTH(ORDER_DATE)) AS SALES_DIFFERENCE
FROM ASSIGNMENT_ecommerce_orders 
GROUP BY MONTH(ORDER_DATE);

-- 49. Find highest order of every category.
SELECT *FROM (
    SELECT CATEGORY,ORDER_ID,SALES_AMOUNT,
     RANK() OVER(PARTITION BY CATEGORY ORDER BY SALES_AMOUNT DESC) AS RNK
FROM ASSIGNMENT_ecommerce_orders 
) CATEGORY_RANK
WHERE RNK = 1;

-- 50. Find customer retention month-wise.
   SELECT CUSTOMER_NAME, MONTH(ORDER_DATE) AS CURRENT_MONTH,
   LAG(MONTH(ORDER_DATE))OVER(PARTITION BY CUSTOMER_NAME ORDER BY ORDER_DATE) AS PREVIOUS_MONTH
 FROM ASSIGNMENT_ecommerce_orders;