SELECT * 
FROM GLOBALSUPERSTORE;

SELECT `ORDER_ID` , REGION
FROM GLOBALSUPERSTORE
WHERE REGION = 'WEST';

SELECT * 
FROM  GLOBALSUPERSTORE
WHERE CATEGORY ='FURNITURE';

SELECT `ORDER_ID` , SALES
FROM GLOBALSUPERSTORE
WHERE SALES > 500;

SELECT `ORDER_ID` , CITY
FROM GLOBALSUPERSTORE
WHERE CITY = 'NEW YORK CITY';

SELECT `ORDER_ID` , PROFIT 
FROM GLOBALSUPERSTORE
WHERE PROFIT < 0;

SELECT `ORDER_ID` , DISCOUNT
FROM GLOBALSUPERSTORE
WHERE DISCOUNT > 0.2;

SELECT `ORDER_ID` , QUANTITY
FROM GLOBALSUPERSTORE
WHERE QUANTITY BETWEEN 3 AND 7;

ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `SHIP MODE` TO SHIP_MODE;

SELECT `ORDER_ID` , SHIP_MODE
FROM GLOBALSUPERSTORE
WHERE SHIP_MODE = 'SECOND CLASS';

SELECT `ORDER_ID` , STATE
FROM GLOBALSUPERSTORE
WHERE STATE IN ('CALIFORNIA','TEXAS');


SELECT `ORDER_ID` , CATEGORY,SALES 
FROM GLOBALSUPERSTORE
WHERE CATEGORY = 'TECHNOLOGY' AND SALES  > 1000;

SELECT `ORDER_ID` , REGION, PROFIT 
FROM GLOBALSUPERSTORE
WHERE REGION = "EAST" OR PROFIT < 0;

ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `CUSTOMER NAME` TO CUSTOMER_NAME ;

SELECT `ORDER_ID` ,CUSTOMER_NAME 
FROM GLOBALSUPERSTORE
WHERE CUSTOMER_NAME LIKE "A%";

ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `PRODUCT NAME` TO PRODUCT_NAME ;

SELECT `ORDER_ID` , PRODUCT_NAME  
FROM GLOBALSUPERSTORE
WHERE PRODUCT_NAME LIKE '%CHAIR%';

ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `POSTAL CODE` TO POSTAL_CODE ;

SELECT POSTAL_CODE
FROM GLOBALSUPERSTORE
WHERE POSTAL_CODE IS NULL; 

SELECT SUM(SALES) AS TOTAL_SALES,REGION 
FROM GLOBALSUPERSTORE
GROUP BY REGION;

SELECT SUM(PROFIT) AS TOTAL_PROFIT 
FROM GLOBALSUPERSTORE
GROUP BY CATEGORY;

ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `SUB-CATEGORY` TO SUB_CATEGORY ;

SELECT SUB_CATEGORY,SUM(QUANTITY) AS TOTAL_QUANTITY
FROM GLOBALSUPERSTORE
 GROUP BY SUB_CATEGORY
 ORDER BY TOTAL_QUANTITY DESC;
 
 SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS
 FROM GLOBALSUPERSTORE
 GROUP BY SHIP_MODE;
 
 ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `CUSTOMER ID` TO CUSTOMER_ID ;
 
 SELECT AVG(SALES) AS AVG_SALES
FROM GLOBALSUPERSTORE
GROUP BY CUSTOMER_ID;

SELECT REGION, CATEGORY,
SUM(SALES) AS TOTAL_SALES, 
 SUM(PROFIT) AS TOTAL_PROFIT
FROM GLOBALSUPERSTORE
GROUP BY REGION, CATEGORY;

SELECT SEGMENT ,AVG(DISCOUNT) AS TOTAL_DISCOUNT
 FROM GLOBALSUPERSTORE
 GROUP BY SEGMENT ;
 
 SELECT REGION, COUNT(CUSTOMER_ID) AS CUSTOMER
 FROM GLOBALSUPERSTORE
 GROUP BY REGION;
 
 SELECT CATEGORY , MIN(PROFIT) AS MIN_PROFIT
 FROM GLOBALSUPERSTORE
 GROUP BY CATEGORY;
 
 SELECT SUB_CATEGORY , MAX(SALES) AS MAX_SALES
 FROM GLOBALSUPERSTORE
 GROUP BY SUB_CATEGORY;
 
 SELECT *
 FROM GLOBALSUPERSTORE
 ORDER BY SALES ASC;
 
 SELECT *
 FROM GLOBALSUPERSTORE
 ORDER BY PROFIT DESC;
 
  SELECT *
 FROM GLOBALSUPERSTORE
 ORDER BY ORDER_DATA DESC;
 
 SELECT CUSTOMER_NAME 
 FROM GLOBALSUPERSTORE
 ORDER BY CUSTOMER_NAME ASC;
 
 SELECT PRODUCT_NAME, CATEGORY
 FROM GLOBALSUPERSTORE
 ORDER BY  PRODUCT_NAME, CATEGORY ASC;
 
 SELECT REGION , SALES 
 FROM GLOBALSUPERSTORE
 ORDER BY REGION ASC, SALES DESC;
 
 SELECT STATE , CITY
 FROM GLOBALSUPERSTORE
 ORDER BY STATE ,CITY ASC;
 
 SELECT SHIP_MODE,ORDER_DATA 
  FROM GLOBALSUPERSTORE
  ORDER BY SHIP_MODE , ORDER_DATA ASC;
  
  SELECT SEGMENT,SALES 
  FROM GLOBALSUPERSTORE
  ORDER BY SEGMENT DESC, SALES ASC;
  
  SELECT CATEGORY ,PROFIT 
  FROM GLOBALSUPERSTORE
  ORDER BY CATEGORY , PROFIT DESC;
  
  SELECT CUSTOMER_ID ,SUM(SALES) AS TOTAL_SALES
  FROM GLOBALSUPERSTORE
  GROUP BY CUSTOMER_ID
  HAVING TOTAL_SALES
  ORDER BY TOTAL_SALES DESC LIMIT 5;

SELECT CUSTOMER_ID ,
COUNT(ORDER_ID) AS  ORDER_COUNT,
SUM(SALES) AS TOTAL_SALES
  FROM GLOBALSUPERSTORE
  GROUP BY CUSTOMER_ID
  HAVING COUNT(ORDER_ID)>5
  ORDER BY TOTAL_SALES DESC;
  
  SELECT SUB_CATEGORY ,COUNT(QUANTITY) AS COUNT_QUANTITY
  FROM GLOBALSUPERSTORE
  GROUP BY SUB_CATEGORY 
  HAVING COUNT_QUANTITY >100 
  ORDER BY COUNT_QUANTITY DESC
  LIMIT 5 ;
  
  SELECT REGION,AVG(SALES) AS AVG_SALES
  FROM GLOBALSUPERSTORE
   GROUP BY REGION
   HAVING AVG_SALES > 300
   ORDER BY AVG_SALES DESC;
   
   SELECT CUSTOMER_ID,SUM(PROFIT) AS TOTAL_PROFIT
   FROM GLOBALSUPERSTORE
   GROUP BY CUSTOMER_ID
   HAVING TOTAL_PROFIT < 0
   ORDER BY TOTAL_PROFIT;
   
   SELECT CATEGORY , SUM(SALES) AS TOTAL_SALES
   FROM GLOBALSUPERSTORE
   GROUP BY CATEGORY
   HAVING TOTAL_SALES > 5000
   LIMIT 3;
   
   SELECT SUB_CATEGORY ,SUM(PROFIT) AS TOTAL_PROFIT
   FROM GLOBALSUPERSTORE
   GROUP BY SUB_CATEGORY
   HAVING TOTAL_PROFIT > 0
   ORDER BY TOTAL_PROFIT ;
   
   SELECT CUSTOMER_ID,AVG(DISCOUNT) AS AVG_DISCOUNT
   FROM GLOBALSUPERSTORE
   GROUP BY CUSTOMER_ID
   HAVING AVG_DISCOUNT > 0.2;
   
   SELECT REGION,COUNT(QUANTITY) AS TOTAL_QUANTITY
   FROM GLOBALSUPERSTORE
   GROUP BY REGION
   HAVING TOTAL_QUANTITY > 200
   ORDER BY TOTAL_QUANTITY DESC;
   
   SELECT CUSTOMER_ID,SUM(SALES) AS TOTAL_SALES
   FROM GLOBALSUPERSTORE
    GROUP BY CUSTOMER_ID
    HAVING TOTAL_SALES > 3000
    ORDER BY TOTAL_SALES DESC
    LIMIT 5;
    
    SELECT SUB_CATEGORY,MAX(DISCOUNT) AS MAX_DISCOUNT
     FROM GLOBALSUPERSTORE
     GROUP BY SUB_CATEGORY
     HAVING MAX_DISCOUNT > 0.5;
     
     SELECT CUSTOMER_NAME,COUNT(ORDER_ID) AS COUNT_ORDER
     FROM GLOBALSUPERSTORE
     GROUP BY  CUSTOMER_NAME
     HAVING COUNT_ORDER > 3
     ORDER BY CUSTOMER_NAME ASC;
     
     SELECT CATEGORY ,COUNT(QUANTITY) AS TOTAL_QUANTITY
     FROM GLOBALSUPERSTORE
     GROUP BY CATEGORY
     HAVING TOTAL_QUANTITY > 150 
     ORDER BY TOTAL_QUANTITY DESC
     LIMIT 2;
     
     SELECT REGION, MIN(PROFIT) AS TOTAL_PROFIT
     FROM GLOBALSUPERSTORE
     GROUP BY REGION
     HAVING TOTAL_PROFIT < 1000
     ORDER BY TOTAL_PROFIT ASC ;
     
     SELECT CUSTOMER_ID,PROFIT,SUM(SALES) AS TOTAL_SALES
      FROM GLOBALSUPERSTORE
      GROUP BY CUSTOMER_ID,PROFIT
      HAVING TOTAL_SALES > 2000
      ORDER BY PROFIT;
      
      SELECT SUB_CATEGORY,AVG(QUANTITY) AS AVG_QUANTITY
      FROM GLOBALSUPERSTORE
      GROUP BY SUB_CATEGORY
      HAVING AVG_QUANTITY > 3;
      
      SELECT CUSTOMER_ID ,SUM(PROFIT) AS TOTAL_PROFIT
      FROM GLOBALSUPERSTORE
      GROUP BY CUSTOMER_ID 
      HAVING  TOTAL_PROFIT > 1000
      ORDER BY CUSTOMER_ID DESC
      LIMIT 4;
      
      SELECT REGION,MAX(SALES) AS MAX_SALES
       FROM GLOBALSUPERSTORE
       GROUP BY REGION
       HAVING MAX_SALES > 2000;
       
       SELECT SUB_CATEGORY,AVG(PROFIT) AS AVG_PROFIT
       FROM GLOBALSUPERSTORE
       GROUP BY SUB_CATEGORY
       HAVING AVG_PROFIT < 50
       ORDER BY AVG_PROFIT ;
       
       SELECT REGION,SUM(SALES) AS TOTAL_SALES
        FROM GLOBALSUPERSTORE
        GROUP BY REGION
        HAVING TOTAL_SALES > 10000
        ORDER BY TOTAL_SALES DESC
        LIMIT 3;
        
        SELECT CUSTOMER_ID,MIN(PROFIT) AS MIN_PROFIT
        FROM GLOBALSUPERSTORE
        GROUP BY CUSTOMER_ID
        HAVING  MIN_PROFIT < 0;
        
        SELECT CATEGORY , AVG(DISCOUNT) AS AVG_DISCOUNT
        FROM GLOBALSUPERSTORE
        GROUP BY CATEGORY 
        HAVING AVG_DISCOUNT > 0.25
        ORDER BY AVG_DISCOUNT DESC;
        
        SELECT SUB_CATEGORY ,SUM(PROFIT) AS TOTAL_PROFIT
         FROM GLOBALSUPERSTORE
         GROUP BY SUB_CATEGORY 
         HAVING TOTAL_PROFIT > 500
         ORDER BY TOTAL_PROFIT  DESC
         LIMIT 5;
         
         SELECT CUSTOMER_ID ,COUNT(QUANTITY) AS COUNT_QUANTITY
         FROM GLOBALSUPERSTORE
         GROUP BY CUSTOMER_ID
         HAVING COUNT_QUANTITY > 50
         ORDER BY COUNT_QUANTITY ;
         
         SELECT REGION , MIN(DISCOUNT) AS MIN_DISCOUNT
         FROM GLOBALSUPERSTORE
         GROUP BY REGION
         HAVING MIN_DISCOUNT =0
         ORDER BY MIN_DISCOUNT DESC;
         
         SELECT CUSTOMER_ID,COUNT(QUANTITY) AS TOTAL_QUANTITY
         FROM GLOBALSUPERSTORE
         GROUP BY CUSTOMER_ID
         HAVING TOTAL_QUANTITY > 30
         ORDER BY TOTAL_QUANTITY DESC
         LIMIT 3;
         
        
        
       
       
       
       
      
      
     
     
     
     
     
     
     
     
     
    
    
   
   
   
   
   
  
  
  
  
  
 
 
 
 
 









