SELECT * 
FROM RETAIL_ORDERS;

SELECT CATEGORY,SUB_CATEGORY,PRODUCT_NAME
FROM RETAIL_ORDERS;

 SELECT CUSTOMER_NAME,CITY
 FROM RETAIL_ORDERS
 WHERE CITY = "HYDERABAD";
 
 SELECT CUSTOMER_NAME,CITY
 FROM RETAIL_ORDERS
 WHERE CITY != "HYDERABAD";
 
 SELECT CUSTOMER_NAME,CITY
 FROM RETAIL_ORDERS
 WHERE CITY <> "HYDERABAD";
 
 SELECT CUSTOMER_NAME,SALES
 FROM RETAIL_ORDERS
 WHERE SALES > 50000;
 
  
  SELECT CUSTOMER_NAME, CITY
  FROM RETAIL_ORDERS
  WHERE CITY ="MUMBAI" OR CITY = "CHENNAI";
  
  SELECT CUSTOMER_NAME, CITY ,CATEGORY
  FROM RETAIL_ORDERS
  WHERE CITY ="MUMBAI" OR CITY ="DELHI" OR CITY = "CHENNAI";
  
  SELECT CUSTOMER_NAME, CATEGORY
  FROM RETAIL_ORDERS
  WHERE NOT CATEGORY ="TECHNOLOGY";
  
  SELECT CUSTOMER_NAME, SALES
  FROM RETAIL_ORDERS
  WHERE SALES BETWEEN 10000 AND 50000;
  
  SELECT * FROM RETAIL_ORDERS;
  
  SELECT CUSTOMER_NAME,ORDER_DATE
  FROM RETAIL_ORDERS
  WHERE ORDER_DATE BETWEEN '2023-01-05' AND '2023-03-05';
  
  SELECT CUSTOMER_NAME,CITY
  FROM RETAIL_ORDERS
  WHERE CITY IN ("CHENNAI","DELHI","MUMBAI") ;
  
  SELECT CUSTOMER_NAME,CITY
  FROM RETAIL_ORDERS
  WHERE CITY  NOT IN ("CHENNAI","DELHI","MUMBAI") ;
  
   SELECT * FROM RETAIL_ORDERS;
   
   SELECT CUSTOMER_NAME
   FROM RETAIL_ORDERS
   WHERE CUSTOMER_NAME LIKE "A%";
  
  SELECT CUSTOMER_NAME
   FROM RETAIL_ORDERS
   WHERE CUSTOMER_NAME LIKE "%Y";
  
  SELECT CUSTOMER_NAME
   FROM RETAIL_ORDERS
   WHERE CUSTOMER_NAME LIKE "%IT%";
  
  SELECT CUSTOMER_NAME
   FROM RETAIL_ORDERS
   WHERE CUSTOMER_NAME LIKE "____";
   
   SELECT * FROM RETAIL_ORDERS;
   
   
   SELECT DISCOUNT
   FROM RETAIL_ORDERS
   WHERE DISCOUNT IS NOT NULL;
   
  SELECT DISCOUNT
   FROM RETAIL_ORDERS
   WHERE DISCOUNT IS NULL;
   
   SELECT SUM(SALES) AS TOTAL_SALES,
		AVG(SALES) AS AVG_SALES,
        MIN(SALES) AS MIN_SALES,
        MAX(SALES) AS MAX_SALES,
        COUNT(SALES) AS TOTAL_ORDERS
   FROM RETAIL_ORDERS; 
   
    SELECT CUSTOMER_NAME, SUM(SALES) AS TOTAL_SALES
    FROM RETAIL_ORDERS
    GROUP BY CUSTOMER_NAME;
   
  SELECT CITY, SUM(SALES) AS TOTAL_SALES
    FROM RETAIL_ORDERS
	GROUP BY CITY;
    
    SELECT CITY,CATEGORY , SUM(SALES) AS TOTAL_SALES
    FROM RETAIL_ORDERS
    GROUP BY CITY, CATEGORY
    ORDER BY CITY, CATEGORY;
   
   SELECT CITY,SUM(SALES)AS TOTAL_SALES
   FROM RETAIL_ORDERS
   GROUP BY CITY
   HAVING SUM(SALES) > 100000;
  
  SELECT CATEGORY,SUM(SALES)AS TOTAL_SALES
   FROM RETAIL_ORDERS
   GROUP BY CATEGORY
   HAVING SUM(SALES) > 100000;
   
   SELECT CITY , COUNT(ORDER_ID) AS COUNT_ORDER
   FROM RETAIL_ORDERS
    GROUP BY CITY
    HAVING COUNT(ORDER_ID) > 3;
    
     SELECT  CUSTOMER_ID , COUNT(CUSTOMER_ID) AS COUNT_CUSTOMER
   FROM RETAIL_ORDERS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 1;
    
     SELECT  CUSTOMER_ID , 
     SUM(SALES) AS TOTAL_SALES,
     COUNT(ORDER_ID) AS TOTAL_ORDERS
   FROM RETAIL_ORDERS
    GROUP BY CUSTOMER_ID
    HAVING SUM(SALES) >2000 AND COUNT(ORDER_ID) > 1;
    
    SELECT SUB_CATEGORY ,
    COUNT(QUANTITY) AS TOTAL_QUANTITY,
    SUM(PROFIT) AS TOTAL_PROFIT
    FROM RETAIL_ORDERS
    GROUP BY SUB_CATEGORY
    HAVING COUNT(QUANTITY) > 3 AND SUM(PROFIT) > 0;
    
    SELECT CATEGORY , CITY ,SUM(SALES) TOTAL_SALES
    FROM  RETAIL_ORDERS
    WHERE CITY = "HYDERABAD"
    GROUP BY CATEGORY,CITY
    HAVING TOTAL_SALES > 50000;
    
    SELECT CITY , CATEGORY , SUM(PROFIT) AS TOTAL_PROFIT 
     FROM  RETAIL_ORDERS
     GROUP BY CITY, CATEGORY 
     HAVING TOTAL_PROFIT > 5000;
     
     SELECT CATEGORY , ORDER_DATE ,SUM(SALES) AS TOTAL_SALES 
     FROM  RETAIL_ORDERS
     WHERE ORDER_DATE > '2023-02-01'
     GROUP BY CATEGORY, ORDER_DATE
     HAVING TOTAL_SALES > 4000;
     
     SELECT CITY, ORDER_DATE, SUM(PROFIT) AS TOTAL_PROFIT
     FROM  RETAIL_ORDERS
     WHERE ORDER_DATE  BETWEEN '2023-03-01' AND '2023-04-30'
     GROUP  BY CITY, ORDER_DATE
     HAVING TOTAL_PROFIT > 4000;
     
      SELECT CATEGORY , ORDER_DATE ,SUM(SALES) AS TOTAL_SALES 
     FROM  RETAIL_ORDERS
     WHERE '2023-02-01'
     GROUP BY CATEGORY, ORDER_DATE
     HAVING TOTAL_SALES > 4000;
     
     SELECT * FROM RETAIL_ORDERS LIMIT 5;
     
     SELECT CUSTOMER_ID,SUM(SALES) AS TOTAL_SALES
     FROM  RETAIL_ORDERS
     GROUP BY CUSTOMER_ID
     ORDER BY SUM(SALES) DESC
     LIMIT 5;
     
     
    
    
    
   
  