CREATE DATABASE NINEAM_CLASS;
USE NINEAM_CLASS;
CREATE TABLE EMPLOYEE_DETAILS
(
  EMPLOYEE_ID INT,
  EMPLOYEE_NAME VARCHAR(50),
  EMP_AGE SMALLINT
);
DESC EMPLOYEE_DETAILS;

ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN DEPARTMENT VARCHAR(30);
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN
(
 POSTAL_CODE INT,
 CITY VARCHAR(30)
);

ALTER TABLE EMPLOYEE_DETAILS MODIFY EMP_AGE TINYINT;
ALTER TABLE EMPLOYEE_DETAILS RENAME TO EMP_DETAILS;
ALTER TABLE EMP_DETAILS DROP COLUMN POSTAL_CODE;
ALTER TABLE EMP_DETAILS;
DESC EMP_DETAILS;

INSERT INTO EMP_DETAILS VALUES
(1,"LIKHITHA",25,"IT","VIZAG");
SELECT * FROM EMP_DETAILS;

INSERT INTO EMP_DETAILS 
VALUES 
(2,"SHERYA",15,"CA","HYD"),
(3,"ROJA",35,"TEACHER","SKML");
SELECT * FROM EMP_DETAILS;


SET SQL_SAFE_UPDATES =0;
SET SQL_SAFE_UPDATES =1;
UPDATE EMP_DETAILS
SET EMP_AGE = 24
WHERE EMPLOYEE_ID = 3;

DELETE FROM EMP_DETAILS
WHERE EMPLOYEE_NAME = "SHERYA";

TRUNCATE TABLE EMP_DETAILS;
DROP TABLE EMP_DETAILS;

