USE NINEAM_CLASS;
SELECT * FROM CUSTOMER_DATA;
SELECT CUSTOMER_NAME,
        UPPER(CUSTOMER_NAME),
        LOWER(CUSTOMER_NAME),
        TRIM(CUSTOMER_NAME),
        LENGTH(TRIM(CUSTOMER_NAME)),
        CONCAT(CUSTOMER_NAME," " , CITY, " ",PHONE," ", EMAIL),
        CONCAT_WS(" ", CUSTOMER_NAME,CITY,PHONE,EMAIL)
FROM CUSTOMER_DATA;

  -- CONCAT_WS - CONCATE WITH SEPARATOR 
  
  -- LPAD, RPAD,SUBSTRING,SUBSTRING_INDEX
 SELECT CITY, LPAD(CITY,20,0),RPAD(CITY,15,"-"),
         SUBSTRING(CITY,4,5),EMAIL,
         SUBSTRING_INDEX(EMAIL,"@",-1)
 FROM CUSTOMER_DATA;
 
 -- ACID PROPERTIES
 /*
 A-ATOMICITY
 C-CONSISTENCY
 I-ISOLATION
 D-DURABILITY
 */
 
 
 
 
  
  